version: '3.7'
services:
    # The Go App
    go-app:
        build: ./go-app
        container_name: go_app
        #restart: "on-failure"
        depends_on:
            - 'mongo'
        environment:
            - PORT=8000
        ports:
            - '8000:8000'
        volumes:
            - './go-app:/opt/go-app:cached'
        networks:
            - app-network

    # MongoDB
    mongo:
        image: 'mongo:4.4'
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: western_user
            MONGO_INITDB_ROOT_PASSWORD: western_mongodb_root_password
            MONGO_INITDB_DATABASE: main
        ports:
            - '27017:27017'
        volumes:
            - dbdata:/data/db
        restart: always
        networks:
            - app-network

#    mongo-express:
#        image: 'mongo-express:latest'
#        container_name: mongo-express
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: western_user
#            ME_CONFIG_MONGODB_ADMINPASSWORD: western_mongodb_root_password
#            ME_CONFIG_MONGODB_SERVER: mongo
#        ports:
#            - '8081:8081'
#        restart: always
#        networks:
#            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
